/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.pizzutti.gui;

import br.pizzutti.entity.Partida;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class MatchPage extends javax.swing.JDialog {

    /**
     * Creates new form MatchPage
     */
    public MatchPage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgChoice = new javax.swing.ButtonGroup();
        bgModo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tbPedra = new javax.swing.JToggleButton();
        jbPcPedra = new javax.swing.JToggleButton();
        tbPapel = new javax.swing.JToggleButton();
        jbPcPapel = new javax.swing.JToggleButton();
        tbTesoura = new javax.swing.JToggleButton();
        jbPcTesoura = new javax.swing.JToggleButton();
        btJoken = new javax.swing.JButton();
        lbResult = new javax.swing.JLabel();
        btProxima = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Partida Jo-Ken-Po");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Partida");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Usuário(a):");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Computador:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("VS");

        bgChoice.add(tbPedra);
        tbPedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/pedra.png"))); // NOI18N
        tbPedra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jbPcPedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/pedra.png"))); // NOI18N
        jbPcPedra.setEnabled(false);
        jbPcPedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPcPedraActionPerformed(evt);
            }
        });

        bgChoice.add(tbPapel);
        tbPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/papel.png"))); // NOI18N
        tbPapel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jbPcPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/papel.png"))); // NOI18N
        jbPcPapel.setEnabled(false);

        bgChoice.add(tbTesoura);
        tbTesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/tesoura.png"))); // NOI18N
        tbTesoura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jbPcTesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/tesoura.png"))); // NOI18N
        jbPcTesoura.setEnabled(false);

        btJoken.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btJoken.setText("Jo - Ken - Po");
        btJoken.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btJoken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJokenActionPerformed(evt);
            }
        });

        lbResult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbResult.setText("---");
        lbResult.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btProxima.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btProxima.setText("Próximo Round");
        btProxima.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btProxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximaActionPerformed(evt);
            }
        });

        jLabel5.setText("By Pedro Pizzutti");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(tbPedra, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tbPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tbTesoura, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel4)
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3)
                                                .addComponent(jbPcTesoura, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jbPcPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jbPcPedra, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(btJoken, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(135, 135, 135)
                                    .addComponent(jLabel1)
                                    .addGap(110, 110, 110)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btProxima))))
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbPcPedra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbPcPapel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPcTesoura))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tbPedra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbPapel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbTesoura)))
                .addGap(27, 27, 27)
                .addComponent(btJoken, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btProxima, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbPcPedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPcPedraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPcPedraActionPerformed

    private void btJokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJokenActionPerformed
        // TODO add your handling code here:
        
        Partida match = new Partida();
        int user_choice = choicePo();
        int comp_choice = match.computador();
        choicePoPc(comp_choice);
        
        String resultado = match.resultado(user_choice, comp_choice);
        
        btJoken.getModel().setEnabled(false);
        
        lbResult.setText(resultado);
        
    }//GEN-LAST:event_btJokenActionPerformed

    private void btProximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximaActionPerformed
        // TODO add your handling code here:
        proximoRound();
    }//GEN-LAST:event_btProximaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MatchPage dialog = new MatchPage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgChoice;
    private javax.swing.ButtonGroup bgModo;
    private javax.swing.JButton btJoken;
    private javax.swing.JButton btProxima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JToggleButton jbPcPapel;
    private javax.swing.JToggleButton jbPcPedra;
    private javax.swing.JToggleButton jbPcTesoura;
    private javax.swing.JLabel lbResult;
    private javax.swing.JToggleButton tbPapel;
    private javax.swing.JToggleButton tbPedra;
    private javax.swing.JToggleButton tbTesoura;
    // End of variables declaration//GEN-END:variables
    
    
    public int choicePo(){
        
        int user_choice = 0;
        
        if(tbPedra.isSelected()){
            
            user_choice = 1;
            
            tbPapel.setEnabled(false);
            tbTesoura.setEnabled(false);
            
        } else if(tbPapel.isSelected()){
            
            user_choice = 2;
            
            tbPedra.setEnabled(false);
            tbTesoura.setEnabled(false);
            
        } else if(tbTesoura.isSelected()){
            
            user_choice = 3;
            
            tbPedra.setEnabled(false);
            tbPapel.setEnabled(false);
            
       
        } else {
            
            JOptionPane.showMessageDialog(this, "Você não selecionou teu Po...\n"
                    + "Selecione para poder jogar!");
        }
        
        return user_choice;
    }
    
    public void choicePoPc(int comp){
        
        int comp_choice = comp;
        
        if(comp_choice == 1){
            jbPcPedra.setEnabled(true);
        } else if(comp_choice == 2){
            jbPcPapel.setEnabled(true);
        } else if(comp_choice == 3){
            jbPcTesoura.setEnabled(true);
        }
    }
    
    public void proximoRound(){
        
        tbPapel.getModel().setEnabled(true);
        tbPedra.getModel().setEnabled(true);
        tbTesoura.getModel().setEnabled(true);
        jbPcPapel.getModel().setEnabled(false);
        jbPcPedra.getModel().setEnabled(false);
        jbPcTesoura.getModel().setEnabled(false);
        btJoken.getModel().setEnabled(true);
        lbResult.setText("---");
    }
}
